preprocessing:
  train_path: ../data/raw/train_orig.csv
  unique_values_path: ../data/processed/unique_values.json
  train_proc_path: ../data/processed/train_num.csv
  test_size: 0.2
  val_size: 0.16
  target_column: cat
  target_column_pred: cat_pred
  sum_columns: ['title', 'description', 'adomain', 'bundle']
  drop_columns: ['text', 'text_count']
  rename_columns:
    cat: cat_orig
  unnecessary_words: ["google", "ru", "app", "apps", "com", "android", "apple", "lv"]
  vectorizer_params:
    max_df: 0.9
    max_features: 9000
  random_state: 10

train:
  n_trials: 10
  random_state: 10
  target_column: cat
  model_path: ../models/model_svc_optuna.joblib
  study_path: ../models/study.joblib
  metrics_path: ../reports/metrics.json
  params_path: ../reports/best_params.json

evaluate:
  data_origin_path: ../data/check/data_origin.csv
  data_num_path: ../data/check/data_num.csv
  data_num_checked_cols_path: ../data/check/data_num_checked_cols.csv

endpoints:
  train: 'http://fastapi:8000/train'
  prediction_input: 'http://fastapi:8000/predict_input'
  prediction_from_file: 'http://fastapi:8000/predict'
#  train: 'http://localhost:8001/train'
#  prediction_input: 'http://localhost:8001/predict_input'
#  prediction_from_file: 'http://localhost:8001/predict'
