preprocessing:
  train_path: ../data/raw/train.csv
  train_proc_path: ../data/processed/train_num.csv
  test_size: 0.2
  val_size: 0.16
  target_column: cat
  target_column_pred: cat_pred
  sum_columns: ['title', 'description', 'adomain', 'bundle']
  drop_columns: ['text', 'text_count']
  rename_columns:
    cat: cat_orig
  unnecessary_words: ["google", "ru", "app", "apps", "com", "android", "apple", "lv", "yandex"]
  vectorizer_params:
#    min_df: 0.0
#    max_df: 0.9
    max_features: 90000
  random_state: 10

train:
  raw_df_path: ../data/raw/train.csv
  num_df_path: ../data/processed/train_num.csv
  cng_df_path: ../data/processed/cng_train.csv
  n_trials: 10
  model_path: ../models/model_svc_optuna.joblib
  study_path: ../models/study.joblib
  metrics_path: ../reports/metrics.json
  params_path: ../reports/best_params.json
  value_path: ../reports/best_value.json

evaluate:
  raw_df_path: ../data/check/data_origin.csv
  num_df_path: ../data/check/num_df.csv
  cng_df_path: ../data/processed/cng_eval.csv
  train_num_df_path: ../data/processed/train_num.csv
  checked_num_df_path: ../data/check/data_num_checked_cols.csv
  len_cols_path: ../reports/len_cols.json
  prediction_path: ../data/check/prediction.csv

endpoints:
#  train: 'http://fastapi:8000/train'
#  prediction_input: 'http://fastapi:8000/predict_input'
#  prediction_from_file: 'http://fastapi:8000/predict'
  train: 'http://localhost:8000/train'
  prediction_input: 'http://localhost:8000/predict_input'
  prediction_from_file: 'http://localhost:8000/predict'
